SQL_STATEMENTS="IF NOT EXISTS 
    (SELECT name  
     FROM master.sys.server_principals
     WHERE name = '$ACCOUNT_USER')
BEGIN
    CREATE LOGIN [$ACCOUNT_USER] WITH PASSWORD='$ACCOUNT_PASSWORD', DEFAULT_DATABASE=[$SQL_DATABASE], CHECK_POLICY=OFF
END

USE [$SQL_DATABASE]

IF NOT EXISTS
    (SELECT name
     FROM sys.database_principals
     WHERE name = '$ACCOUNT_USER')
BEGIN
    CREATE USER [$ACCOUNT_USER] FOR LOGIN [$ACCOUNT_USER] WITH DEFAULT_SCHEMA=[dbo]
    ALTER ROLE db_owner ADD MEMBER [$ACCOUNT_USER]
END"

/usr/local/bin/mssql -s $SQL_SERVER -d "$SQL_DATABASE" -u "$SQL_USER" -p "$SQL_PASSWORD" --query "$SQL_STATEMENTS"